# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

steps:
- task: Gradle@2
  displayName: 'Build project'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: Gradle@3
  displayName: 'Build image'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'dockerBuild'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: DockerCompose@0
  displayName: 'Push image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(02ed0353-2c61-416a-a30d-b24cff915791)'
    azureContainerRegistry: '{"loginServer":"micronauttw.azurecr.io", "id" : "/subscriptions/02ed0353-2c61-416a-a30d-b24cff915791/resourceGroups/FirstMicronautTest/providers/Microsoft.ContainerRegistry/registries/micronauttw"}'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true